namespace Rowles.Toolbox.Core.WebNetwork;

public static class PortReferenceCore
{
    public sealed record PortEntry(int Number, string Protocol, string Service, string Description);

    public static string ProtocolBadge(string protocol) => protocol switch
    {
        "TCP" => "bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300",
        "UDP" => "bg-yellow-100 dark:bg-yellow-900 text-yellow-700 dark:text-yellow-300",
        _ => "bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300",
    };

    public static readonly List<PortEntry> AllPorts =
    [
        new(7, "TCP/UDP", "Echo", "Echo protocol — returns data received"),
        new(20, "TCP", "FTP Data", "File Transfer Protocol — data transfer channel"),
        new(21, "TCP", "FTP Control", "File Transfer Protocol — command/control channel"),
        new(22, "TCP", "SSH", "Secure Shell — encrypted remote login and command execution"),
        new(23, "TCP", "Telnet", "Telnet — unencrypted remote login (insecure)"),
        new(25, "TCP", "SMTP", "Simple Mail Transfer Protocol — email delivery"),
        new(43, "TCP", "WHOIS", "WHOIS directory service — domain registration lookups"),
        new(53, "TCP/UDP", "DNS", "Domain Name System — hostname to IP resolution"),
        new(67, "UDP", "DHCP Server", "Dynamic Host Configuration Protocol — server"),
        new(68, "UDP", "DHCP Client", "Dynamic Host Configuration Protocol — client"),
        new(69, "UDP", "TFTP", "Trivial File Transfer Protocol — simple file transfer"),
        new(80, "TCP", "HTTP", "Hypertext Transfer Protocol — web traffic"),
        new(88, "TCP/UDP", "Kerberos", "Kerberos authentication protocol"),
        new(110, "TCP", "POP3", "Post Office Protocol v3 — email retrieval"),
        new(111, "TCP/UDP", "RPC", "Remote Procedure Call — Sun RPC portmapper"),
        new(119, "TCP", "NNTP", "Network News Transfer Protocol — Usenet"),
        new(123, "UDP", "NTP", "Network Time Protocol — clock synchronisation"),
        new(135, "TCP", "MS RPC", "Microsoft RPC endpoint mapper"),
        new(137, "UDP", "NetBIOS NS", "NetBIOS Name Service"),
        new(138, "UDP", "NetBIOS DGM", "NetBIOS Datagram Service"),
        new(139, "TCP", "NetBIOS SSN", "NetBIOS Session Service — file/printer sharing"),
        new(143, "TCP", "IMAP", "Internet Message Access Protocol — email retrieval"),
        new(161, "UDP", "SNMP", "Simple Network Management Protocol — monitoring"),
        new(162, "UDP", "SNMP Trap", "SNMP Trap — alert notifications"),
        new(179, "TCP", "BGP", "Border Gateway Protocol — internet routing"),
        new(194, "TCP", "IRC", "Internet Relay Chat"),
        new(389, "TCP/UDP", "LDAP", "Lightweight Directory Access Protocol"),
        new(443, "TCP", "HTTPS", "HTTP over TLS/SSL — secure web traffic"),
        new(445, "TCP", "SMB", "Server Message Block — Windows file sharing"),
        new(464, "TCP/UDP", "Kerberos Pwd", "Kerberos password change"),
        new(465, "TCP", "SMTPS", "SMTP over TLS — encrypted email submission (legacy)"),
        new(500, "UDP", "IKE", "Internet Key Exchange — IPsec VPN"),
        new(514, "UDP", "Syslog", "System logging protocol"),
        new(515, "TCP", "LPD", "Line Printer Daemon — network printing"),
        new(520, "UDP", "RIP", "Routing Information Protocol"),
        new(530, "TCP/UDP", "RPC", "Remote Procedure Call"),
        new(543, "TCP", "Klogin", "Kerberos login"),
        new(544, "TCP", "Kshell", "Kerberos remote shell"),
        new(546, "UDP", "DHCPv6 Client", "DHCPv6 client"),
        new(547, "UDP", "DHCPv6 Server", "DHCPv6 server"),
        new(554, "TCP", "RTSP", "Real Time Streaming Protocol — media streaming"),
        new(587, "TCP", "SMTP Submission", "SMTP message submission with STARTTLS"),
        new(631, "TCP/UDP", "IPP", "Internet Printing Protocol (CUPS)"),
        new(636, "TCP", "LDAPS", "LDAP over TLS/SSL — secure directory access"),
        new(853, "TCP", "DNS over TLS", "Encrypted DNS queries (DoT)"),
        new(873, "TCP", "rsync", "rsync file synchronisation"),
        new(993, "TCP", "IMAPS", "IMAP over TLS/SSL — secure email retrieval"),
        new(995, "TCP", "POP3S", "POP3 over TLS/SSL — secure email retrieval"),
        new(1080, "TCP", "SOCKS", "SOCKS proxy protocol"),
        new(1194, "UDP", "OpenVPN", "OpenVPN — open-source VPN"),
        new(1433, "TCP", "MSSQL", "Microsoft SQL Server"),
        new(1434, "UDP", "MSSQL Browser", "Microsoft SQL Server Browser"),
        new(1521, "TCP", "Oracle DB", "Oracle Database listener"),
        new(1723, "TCP", "PPTP", "Point-to-Point Tunnelling Protocol VPN"),
        new(1883, "TCP", "MQTT", "Message Queuing Telemetry Transport — IoT messaging"),
        new(2049, "TCP/UDP", "NFS", "Network File System"),
        new(2181, "TCP", "ZooKeeper", "Apache ZooKeeper coordination service"),
        new(2379, "TCP", "etcd Client", "etcd distributed key-value store (client)"),
        new(2380, "TCP", "etcd Peer", "etcd distributed key-value store (peer)"),
        new(3000, "TCP", "Dev Server", "Common development server port (Node.js, Grafana)"),
        new(3306, "TCP", "MySQL", "MySQL / MariaDB database"),
        new(3389, "TCP", "RDP", "Remote Desktop Protocol — Windows remote access"),
        new(4369, "TCP", "EPMD", "Erlang Port Mapper Daemon"),
        new(4443, "TCP", "Pharos", "Common alternative HTTPS port"),
        new(5000, "TCP", "Dev Server", "Common development server port (Flask, ASP.NET)"),
        new(5060, "TCP/UDP", "SIP", "Session Initiation Protocol — VoIP signalling"),
        new(5061, "TCP", "SIP TLS", "SIP over TLS — secure VoIP signalling"),
        new(5222, "TCP", "XMPP", "Extensible Messaging and Presence Protocol — chat"),
        new(5432, "TCP", "PostgreSQL", "PostgreSQL database"),
        new(5672, "TCP", "AMQP", "Advanced Message Queuing Protocol (RabbitMQ)"),
        new(5900, "TCP", "VNC", "Virtual Network Computing — remote desktop"),
        new(5984, "TCP", "CouchDB", "Apache CouchDB REST API"),
        new(6379, "TCP", "Redis", "Redis in-memory data store"),
        new(6443, "TCP", "Kubernetes API", "Kubernetes API server"),
        new(6660, "TCP", "IRC Alt", "Internet Relay Chat (alternative range start)"),
        new(6667, "TCP", "IRC", "Internet Relay Chat (default)"),
        new(7000, "TCP", "Cassandra", "Apache Cassandra inter-node"),
        new(7474, "TCP", "Neo4j HTTP", "Neo4j graph database HTTP API"),
        new(8080, "TCP", "HTTP Alt", "Common alternative HTTP port (proxies, dev servers)"),
        new(8443, "TCP", "HTTPS Alt", "Common alternative HTTPS port"),
        new(8883, "TCP", "MQTT TLS", "MQTT over TLS — secure IoT messaging"),
        new(8888, "TCP", "HTTP Alt", "Alternative HTTP port (Jupyter Notebook)"),
        new(9000, "TCP", "SonarQube", "SonarQube code quality platform"),
        new(9042, "TCP", "Cassandra CQL", "Apache Cassandra native transport (CQL)"),
        new(9090, "TCP", "Prometheus", "Prometheus monitoring metrics"),
        new(9092, "TCP", "Kafka", "Apache Kafka message broker"),
        new(9200, "TCP", "Elasticsearch", "Elasticsearch REST API"),
        new(9300, "TCP", "Elasticsearch", "Elasticsearch inter-node transport"),
        new(9418, "TCP", "Git", "Git protocol (native, unauthenticated)"),
        new(10000, "TCP", "Webmin", "Webmin web-based system admin"),
        new(11211, "TCP/UDP", "Memcached", "Memcached distributed cache"),
        new(15672, "TCP", "RabbitMQ Mgmt", "RabbitMQ management web UI"),
        new(25565, "TCP", "Minecraft", "Minecraft game server"),
        new(27017, "TCP", "MongoDB", "MongoDB database"),
        new(27018, "TCP", "MongoDB Shard", "MongoDB shard server"),
        new(27019, "TCP", "MongoDB Config", "MongoDB config server"),
        new(28017, "TCP", "MongoDB Web", "MongoDB web status page (legacy)"),
        new(33060, "TCP", "MySQL X", "MySQL X Protocol (document store)"),
        new(44818, "TCP/UDP", "EtherNet/IP", "EtherNet/IP industrial protocol"),
        new(50000, "TCP", "SAP", "SAP application server"),
        new(51413, "TCP/UDP", "BitTorrent", "BitTorrent default client port"),
    ];
}
